apiVersion: v1
kind: Service
metadata:
  name: match-fun-words-service
spec:
  type: LoadBalancer
  selector:
    app: match-fun-words
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080